apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: commands
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
  - name: namespace
    value: "chr-staging.servicebus.windows.net"
  - name: maxConcurrentHandlers 
    value: 1

